POST http://localhost:5031/user/register
Content-Type: application/json

{
    "nome": "Bruno",
    "email": "bruno.com",
    "password": "60"
}
###
POST http://localhost:5031/user/login
Content-Type: application/json

{
    "nome": "Wesk",
    "email": "weskar.queiroz",
    "password": "30"
}
###
GET http://localhost:5031/user/listar

###
PUT http://localhost:5031/user/alterar/1
Content-Type: application/json

{
    "nome": "Wesk",
    "email": "weskar.queiroz",
    "password": "30",
    "taskIds": []
}

###
DELETE http://localhost:5031/user/deletar/3

###
###
POST http://localhost:5031/task/create
Content-Type: application/json

{
    "name": "teste6",
    "description": "ewqeqweqwe",
    "status": "pendente",
    "userIds": [1, 2]
}
###
GET http://localhost:5031/task/listar

###
PUT http://localhost:5031/task/editar/1
Content-Type: application/json

{
    "name": "teste6",
    "description": "ewqeqweqwe",
    "status": "pendente",
    "userIds": [1]
}

###
DELETE http://localhost:5031/task/deletar/2

###
###